### ISSUE TITLE
Can't access Management API

### ISSUE THREAD

**Issue by bertsss** [CassiaNetworks/CassiaSDKGuide#11]
I can't access /cassia/info locally even I'm successfully logged in. It's having `Reason: CORS header ‘Access-Control-Allow-Origin’ missing` error

**Comment by kevin-cassia** [comment]
Hi @bertsss ! Thanks for reaching out here.
Can you describe how you are calling the /cassia/info API?

In the gateway settings (under the Other tab), there should be an "Allow Origin" field. You can try entering * for testing purposes. If you have a specific origin domain that you would like to specify, you can do so.

For more information, you can go to section 5.5 of the Cassia User Manual: https://www.cassianetworks.com/download/docs/Cassia_User_Manual.pdf

<img width="615" alt="Screen Shot 2021-07-21 at 12 55 03 AM" src="https://user-images.githubusercontent.com/47803056/126452851-98558e37-0cc6-4920-912d-fa219c488b61.png">


By the way, if you would like quicker assistance, please reach out to Cassia Support at:
https://www.cassianetworks.com/support

- Kevin

**Comment by kevin-cassia** [comment]
@bertsss , was your /cassia/info API issue resolved?

If not, please also take a look at the following information:

When using the /cassia/* APIs in Standalone Router mode, you may need to log in to the gateway first. To do so, send a POST request with the following instructions:

Make sure the request header contains:
`Content-Type: application/x-www-form-urlencoded
`
The form data should contain the username and password of the gateway login. For example:
`username=admin&password=admin2
`
Send the POST request to the login API. For example:
`http://{gateway ip}/cassia/login
`
After the POST request returns a 200 OK response, you should be able to call the /cassia/* APIs without getting a Login page HTML response.

**Comment by kevin-cassia** [comment]
Hello @bertsss,

I'll close this issue for now. If you have any additional questions or concerns, please feel free to reach back out.

Thanks,
Kevin
