### ISSUE TITLE
Getting version error

### ISSUE THREAD

**Issue by srikanth-kuriyala** [CassiaNetworks/CassiaSDKGuide#8]
While uploading a container on the router it giving the message "Version error". We checked in logs there are no details about this error.

Please help us to solve this problem.

![imgo](https://user-images.githubusercontent.com/40609145/98074355-482d8a00-1e90-11eb-9b72-f19152aa9cb8.jpeg)

**Comment by kevin-cassia** [comment]
Hi Srikanth,

Thanks for reporting this. Sorry for the late reply. You can reach us faster at the Cassia Networks Support page: https://www.cassianetworks.com/support

We'll be checking here regularly from now on as well.

Is this issue already resolved for you, or do you need us to take a look at this?

Thanks,
Kevin

**Comment by srikanth-kuriyala** [comment]
It got resolved. Thank you.
