### ISSUE TITLE
C# code samples for REST APIs

### ISSUE THREAD

**Issue by mesgar** [CassiaNetworks/CassiaSDKGuide#9]
Hi,

Need a C# sample of CassiaSDK.
A C# version of acScan.js would help.

Regards

**Comment by mesgar** [comment]
I wrote a client App using HttpClient accessing router via AC.
I'm calling the Server-Sent Events (SSE) API and getting an infinite loop.
GET http://{your AC domain}/api/gap/nodes?event=1&mac=<router-mac>&filter_mac=<mac1>,<mac2>, … , <macX>

This is working fine.

What I want to do in my App is to create a timer loop and read data from BLE device every 10 minutes.
Which API should I use?
I really appreciate a C# version of CassiaSDK.

**Comment by kevin-cassia** [comment]
Hi Mesgar,

Thanks for reaching out here! We will plan to add more code examples, and C# is something we will plan to work on.

About the SSE API, you can try using the HttpClient.GetStreamAsync method.
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=net-5.0

I saw an article that may be helpful in building a simple SSE handler for .NET:
https://makolyte.com/event-driven-dotnet-how-to-consume-an-sse-endpoint-with-httpclient

If you have any development questions, you are free to contact our support here:
https://www.cassianetworks.com/support

**Comment by kevin-cassia** [comment]
> What I want to do in my App is to create a timer loop and read data from BLE device every 10 minutes.
> Which API should I use?
> I really appreciate a C# version of CassiaSDK.

If you want to create this application, the APIs involved would be the following:

Scan API:
https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API#scan-bluetooth-devices

Connect/Disconnect API:
https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API#connectdisconnect-to-a-target-device

An alternative to the normal Connect/Disconnect API is the Batch Connect/Disconnect API:
https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API#batch-connectdisconnect-to-a-target-device-v20-and-above

Discover GATT Services and Characteristics API:
https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API#discover-gatt-services-and-characteristics

Read API:
https://github.com/CassiaNetworks/CassiaSDKGuide/wiki/RESTful-API#readwrite-the-value-of-a-specific-characteristic

When you run the Scan API and select your device advertisement data, make sure to clean up the SSE stream. It looks like one way to do this is to use a cancellation token for the HttpClient.GetStreamAsync method:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-5.0

Method definition:
public System.Threading.Tasks.Task<System.IO.Stream> GetStreamAsync (string? requestUri, System.Threading.CancellationToken cancellationToken);

**Comment by kevin-cassia** [comment]
Please feel free to reach out again if you have any questions!
For now, I'll close this case.
